# Generated by Django 6.0.5 on 2026-05-12 15:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, unique=True)),
                ('coefficient', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poids', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='academics.cataloguemodule')),
            ],
            options={
                'ordering': ['module__intitule', 'nom'],
                'unique_together': {('module', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('verrouillee', 'Verrouillée')], default='ouverte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='ModuleChoisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_choix', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_choisis', to='academics.inscription')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='academics.cataloguemodule')),
            ],
            options={
                'ordering': ['module__intitule'],
                'unique_together': {('inscription', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='academics.categorieevaluation')),
                ('module_choisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.modulechoisi')),
            ],
            options={
                'ordering': ['-date_saisie'],
                'unique_together': {('module_choisi', 'categorie')},
            },
        ),
    ]
