# Generated by Django 5.2.12 on 2026-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_cataloguemodule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_saisie',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
